---
name: Roadmap Entry
description: Add a new entry to the roadmap
type: task
labels:
  - needs-triage
body:
  - type: markdown
    attributes:
      value: >
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT OR FEATURE REQUESTS!**
        Please use our [Support Center](https://app.lizardbyte.dev/support) for support issues.
        Entries added by non-members will be ignored.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this item?
      description: Please search to see if an issue already exists.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: _repositories
    attributes:
      label: Repositories
      description: Select the repo(s) this item applies to. You can select multiple repos.
      multiple: true
      options:
        - TODO
  - type: dropdown
    id: stack
    attributes:
      label: Languages/Skills/Technologies
      description: |
        Select the languages/skills/technologies needed to complete this item.
        You can select multiple options.
      multiple: true
      options:
        - Android
        - Bash/Shell/Scripting
        - C
        - C++
        - C#
        - CMake
        - CSS
        - Docker
        - Documentation
        - FFMpeg
        - git
        - GitHub actions
        - Go
        - HTML
        - iOS
        - Java
        - JavaScript
        - Kotlin
        - Legal/Licensing
        - Linux
        - Markdown
        - macOS
        - Objective-C
        - packaging
        - Python
        - Rest API
        - Ruby
        - Rust
        - SQL
        - TypeScript
        - Video encoding/decoding
        - Vue
        - Windows
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide details about this roadmap item
      placeholder: Describe what needs to be done, why it's important, and any other relevant details.
    validations:
      required: true
  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: |
        How much effort is required to complete this item?
        - Small (1-2 days)
        - Medium (3-5 days)
        - Large (1-2 weeks)
        - Extra Large (2+ weeks)
      options:
        - effort:Small
        - effort:Medium
        - effort:Large
        - effort:Extra-Large
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What priority level should this roadmap item have?
      options:
        - priority:Critical
        - priority:High
        - priority:Medium
        - priority:Low
    validations:
      required: true
  - type: dropdown
    id: milestone
    attributes:
      label: Target Milestone
      description: When do you expect this item to be completed?
      options:
        - 1-3 months
        - 3-6 months
        - 6+ months
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies or prerequisites for this roadmap item.
      placeholder: 'e.g., "Requires completion of #123"'
